### ISSUE TITLE
Its hard to understand what is wrong with this error

### ISSUE THREAD

**Issue by vongohren** [decentralized-identity/ion-tools#16]
Im trying to make a ION did with this setup, but get a strange error which does not lead me to anything. See after code

```
    const key = await Bls12381G2KeyPair.generate();
    const jwk = key.toJsonWebKeyPair();
    const did = new ION.DID({
      content: {
        publicKeys: [
          {
            id: 'primary-issuing',
            type: key.type,
            publicKeyJwk: jwk.publicKeyJwk,
            purposes: [ 'assertionMethod' ]
          }
        ],
        services: [
          {
            id: 'did-comm-agent',
            type: 'DIDCommMessaging',
            serviceEndpoint: 'https://mymagicaldidcomurl/messaging',
            accept:[
              "didcomm/v2",
              "didcomm/aip2;env=rfc587"
            ],
          }
        ]
      }
    });
```

`Unexpected 5xx response: {"requestId":"1cbecd445bc68f48a1d34a257946d24c","date":"Wed, 22 Sep 2021 14:37:29 GMT","message":"continuation_storage_uncaught_exception: Error: document_composer_service_has_missing_or_unknown_property"}`

Im not finding any place this is referenced in the SDK or the tool itself.
How can I debug this? I thought it was all up to speed.

```
Things work with this one, so just keen on understanding
```
    let authnKeys = await ION.generateKeyPair();
    let did = new ION.DID({
      content: {
        publicKeys: [
          {
            id: 'key-1',
            type: 'EcdsaSecp256k1VerificationKey2019',
            publicKeyJwk: authnKeys.publicJwk,
            purposes: [ 'authentication' ]
          }
        ],
        services: [
          {
            id: 'domain-1',
            type: 'LinkedDomains',
            serviceEndpoint: 'https://foo.example.com'
          }
        ]
      }
    });
```

**Comment by OR13** [comment]
ION probably does not support:

```
{
            id: 'did-comm-agent',
            type: 'DIDCommMessaging',
            serviceEndpoint: 'https://mymagicaldidcomurl/messaging',
            accept:[
              "didcomm/v2",
              "didcomm/aip2;env=rfc587"
            ],
          }
```

likely `accept` which is not defined in did core.

**Comment by brianorwhatever** [comment]
From did core

> Each service extension MAY include additional properties and MAY further restrict the properties associated with the extension.

That's a heck of a lot of optionality :)

**Comment by kdenhartog** [comment]
The one issue I see as potentially a problem with the key portion of the document is that `key.type` is likely `Bls12381G1Key2020` where as we had to use JsonWebKey2020 to get it to work. I was thinking that was because the relying party needed it that way rather than the ION node.

I'd suspect @OR13 is onto the actual problem at hand (something wrong with the service portion) because we've got Bls based jwks working in our implementation. Try pulling that part out and creating a DID document with only the key first.

**Comment by csuwildcat** [comment]
Yes, ION doesn't accept arbitrary keys at the service object top level, but does within the serviceEndpoint property.

**Comment by vongohren** [comment]
Thanks for all this great feedback! I have removed the 'accept' inside service blob, as @OR13 mentioned, and it worked, so will close this. But follow up with a minor discussion. 

Even with the key that @kdenhartog mentioned as the output it works. So I will continue to use this if that is the proper way to do it? Or shall one use JSON web key2020? Is the key type representing its value, or the type of key behind it the value?

**Comment by kdenhartog** [comment]
I think the reason we needed to switch to JsonWebKey2020 was because contexts for other types were missing the `publicKeyJwk` property and so the public key was being dropped from the did document when it was being loaded by a document loader to verify credentials with vc.js. I believe this was specific to the digital bazaar libraries we were using though and you may not encounter them if you use a different library or a different credential format.
